Test Integration test

diff --git a/project/3_CI_CD/Jenkinsfile b/project/3_CI_CD/Jenkinsfile
--- a/project/3_CI_CD/Jenkinsfile
+++ b/project/3_CI_CD/Jenkinsfile
@@ -133,52 +133,52 @@ pipeline {
 
         }
 
-        // stage('Integration test for Score code') {
+        stage('Integration test for Score code') {
 
-        //     // parallel{
+            // parallel{
 
-        //     //     stage("Run tests") {
+            //     stage("Run tests") {
 
-        //             agent any
+                    agent any
 
-        //             steps {
+                    steps {
 
-        //                 script {
+                        script {
 
-        //                     docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
-        //                         docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
-        //                         }
+                            docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
+                                docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
+                                }
 
-        //                     docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
+                            docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
 
-        //                             env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
-        //                             sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
-        //                             env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
-        //                             sh("echo ${env.EXECUTION_ID}")
-        //                             sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
-        //                             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
-        //                             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
-        //                             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
-        //                             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
-        //                             sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
-        //                         }
-        //                     }
-        //                 }
-        //             }
+                                    env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
+                                    sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
+                                    env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
+                                    sh("echo ${env.EXECUTION_ID}")
+                                    sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
+                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
+                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
+                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
+                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
+                                    sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
+                                }
+                            }
+                        }
+                    }
 
-        //             post {
+                    post {
 
-        //             success {
-        //                     echo 'Score code file successfully passed Unit Test!'
-        //                 }
+                    success {
+                            echo 'Score code file successfully passed Unit Test!'
+                        }
 
-        //             failure {
-        //                     echo 'Code failed the Unit test, please see logs.'
-        //                 }
-        //             }
-        //     //     }
-        //     // }
-        // }
+                    failure {
+                            echo 'Code failed the Unit test, please see logs.'
+                        }
+                    }
+            //     }
+            // }
+        }
 
         // stage('Model MetaData Quality Test') {
 
